config/routes.rb
Rails.application.routes.draw do
  resources :prices do
    collection do
      get 'prices_macd'
    end
  end

  root 'prices#index'

end

app/models/chart_datum.rb
class ChartDatum < ActiveRecord::Base
  def self.parse_chart
    start_date = ChartDatum.last.created_at

    prices = Price.where(created_at: start_date..(start_date + 15.minutes))

    if prices.present?
      volume = prices.last.volume - prices.first.volume

      volume = 0 if volume < 0

      chart_datum = ChartDatum.create(
        high:   prices.order(last_order: :DESC).first.last_order,
        low:    prices.order(last_order: :ASC).first.last_order,
        open:   prices.first.last_order,
        close:  prices.last.last_order,
        volume: volume
      )
    end
  end

  def one_day_ago
    ChartDatum.where(created_at: (created_at - 1.minute)..(created_at + 1.minute)).first
  end
end

app/models/price.rb
require 'open-uri'
class Price < ActiveRecord::Base
  def self.parse_ticker
    self.delay(run_at: Time.now + 9.seconds).parse_ticker

    ticker_data = JSON.load(open('https://koinim.com/ticker'))

    self.create(
      sell:        ticker_data["sell"],
      high:        ticker_data["high"],
      buy:         ticker_data["buy"],
      change_rate: ticker_data["change_rate"],
      bid:         ticker_data["bid"],
      wavg:        ticker_data["wavg"],
      last_order:  ticker_data["last_order"],
      volume:      ticker_data["volume"],
      low:         ticker_data["low"],
      ask:         ticker_data["ask"],
      avg:         ticker_data["avg"]
    )
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/prices_controller.rb
class PricesController < ApplicationController
  before_action :set_price, only: [:show, :edit, :update, :destroy]

  # GET /prices
  # GET /prices.json
  def index
    @prices       = ChartDatum.last(192)
    ohlc          = []
    volume        = []
    groupingUnits = [['week', [1]], ['month', [1, 2, 3, 4, 6]]]
  end

  def prices_macd
    @prices = ChartDatum.last(192)
  end

  # GET /prices/1
  # GET /prices/1.json
  def show
  end

  # GET /prices/new
  def new
    @price = Price.new
  end

  # GET /prices/1/edit
  def edit
  end

  # POST /prices
  # POST /prices.json
  def create
    @price = Price.new(price_params)

    respond_to do |format|
      if @price.save
        format.html { redirect_to @price, notice: 'Price was successfully created.' }
        format.json { render :show, status: :created, location: @price }
      else
        format.html { render :new }
        format.json { render json: @price.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /prices/1
  # PATCH/PUT /prices/1.json
  def update
    respond_to do |format|
      if @price.update(price_params)
        format.html { redirect_to @price, notice: 'Price was successfully updated.' }
        format.json { render :show, status: :ok, location: @price }
      else
        format.html { render :edit }
        format.json { render json: @price.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /prices/1
  # DELETE /prices/1.json
  def destroy
    @price.destroy
    respond_to do |format|
      format.html { redirect_to prices_url, notice: 'Price was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
  # Use callbacks to share common setup or constraints between actions.
  def set_price
    @price = Price.find(params[:id])
  end

  # Never trust parameters from the scary internet, only allow the white list through.
  def price_params
    params.require(:price).permit(:sell, :high, :buy, :change_rate, :bid, :wavg, :last_order, :volume, :low, :ask, :avg)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/prices_helper.rb
module PricesHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>BtcTracker</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/prices/_form.html.erb
<%= form_for(@price) do |f| %>
  <% if @price.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@price.errors.count, "error") %> prohibited this price from being saved:</h2>

      <ul>
      <% @price.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :sell %><br>
    <%= f.text_field :sell %>
  </div>
  <div class="field">
    <%= f.label :high %><br>
    <%= f.text_field :high %>
  </div>
  <div class="field">
    <%= f.label :buy %><br>
    <%= f.text_field :buy %>
  </div>
  <div class="field">
    <%= f.label :change_rate %><br>
    <%= f.text_field :change_rate %>
  </div>
  <div class="field">
    <%= f.label :bid %><br>
    <%= f.text_field :bid %>
  </div>
  <div class="field">
    <%= f.label :wavg %><br>
    <%= f.text_field :wavg %>
  </div>
  <div class="field">
    <%= f.label :last_order %><br>
    <%= f.text_field :last_order %>
  </div>
  <div class="field">
    <%= f.label :volume %><br>
    <%= f.text_field :volume %>
  </div>
  <div class="field">
    <%= f.label :low %><br>
    <%= f.text_field :low %>
  </div>
  <div class="field">
    <%= f.label :ask %><br>
    <%= f.text_field :ask %>
  </div>
  <div class="field">
    <%= f.label :avg %><br>
    <%= f.text_field :avg %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/prices/edit.html.erb
<h1>Editing Price</h1>

<%= render 'form' %>

<%= link_to 'Show', @price %> |
<%= link_to 'Back', prices_path %>

app/views/prices/index.html.erb
<div id="some_id"></div>

<div id="container"></div>

<script type="text/javascript">
  $(function () {
    $.getJSON('/prices.json', function (data) {
      // split the data set into ohlc and volume
      var ohlc = [],
        volume = [],
        dataLength = data.length,
        // set the allowed units for data grouping
        groupingUnits = [[
          'hour',                         // unit name
          [0.25]                             // allowed multiples
        ]],
        
        i = 0;
      
      for (i; i < dataLength; i += 1) {
        ohlc.push([
          data[i].created_at, // the date
          data[i].open, // open
          data[i].high, // high
          data[i].low, // low
          data[i].close // close
        ]);
        
        volume.push([
          data[i].created_at, // the date
          data[i].volume // the volume
        ]);
      }
      
      
      // create the chart
      $('#some_id').highcharts('StockChart', {
        
        rangeSelector: {
          selected: 1
        },
        
        title: {
          text: 'Koinim Fiyat Grafiği'
        },
        
        yAxis: [{
          labels: {
            align: 'right',
            x: -3
          },
          title: {
            text: 'OHLC'
          },
          height: '60%',
          lineWidth: 2
        }, {
          labels: {
            align: 'right',
            x: -3
          },
          title: {
            text: 'Volume'
          },
          top: '65%',
          height: '35%',
          offset: 0,
          lineWidth: 2
        }],
        
        series: [{
          type: 'candlestick',
          name: 'Koinim',
          data: ohlc,
          dataGrouping: {
            units: groupingUnits
          }
        }, {
          type: 'column',
          name: 'Volume',
          data: volume,
          yAxis: 1,
          dataGrouping: {
            units: groupingUnits
          }
        }]
      });
    });
  });
  
  $.getJSON('/prices/prices_macd', function (data) {
    
    var ohlc = [];
    var dataLength = data.length;
    // set the allowed units for data grouping
    
    var i = 0;
    
    for (i; i < dataLength; i += 1) {
      ohlc.push([
        data[i].created_at, // the date
        data[i].high // the volume
      ]);
    }
    
    $('#container').highcharts('StockChart', {
      
      title: {
        text: 'MACD of AAPL stock price'
      },
      
      subtitle: {
        text: 'From may 15, 2006 to May 10, 2013'
      },
      
      yAxis: [{
        title: {
          text: 'Price'
        },
        height: 200,
        plotLines: [{
          value: 0,
          width: 1,
          color: '#808080'
        }]
      }, {
        title: {
          text: 'MACD'
        },
        top: 300,
        height: 100,
        offset: 0,
        lineWidth: 2
      }],
      
      tooltip: {
        crosshairs: true,
        shared: true
      },
      
      rangeSelector: {
        selected: 1
      },
      
      legend: {
        enabled: true,
        layout: 'vertical',
        align: 'right',
        verticalAlign: 'middle',
        borderWidth: 0
      },
      
      plotOptions: {
        series: {
          marker: {
            enabled: false,
          }
        }
      },
      
      series: [{
        name: 'AAPL Stock Price',
        type: 'line',
        id: 'primary',
        data: ohlc
      }, {
        name: 'MACD',
        linkedTo: 'primary',
        yAxis: 1,
        showInLegend: true,
        type: 'trendline',
        algorithm: 'MACD'
        
      }, {
        name: 'Signal line',
        linkedTo: 'primary',
        yAxis: 1,
        showInLegend: true,
        type: 'trendline',
        algorithm: 'signalLine'
        
      }, {
        name: 'Histogram',
        linkedTo: 'primary',
        yAxis: 1,
        showInLegend: true,
        type: 'histogram'
        
      }]
    });
  });
</script>

app/views/prices/new.html.erb
<h1>New Price</h1>

<%= render 'form' %>

<%= link_to 'Back', prices_path %>

app/views/prices/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Sell:</strong>
  <%= @price.sell %>
</p>

<p>
  <strong>High:</strong>
  <%= @price.high %>
</p>

<p>
  <strong>Buy:</strong>
  <%= @price.buy %>
</p>

<p>
  <strong>Change rate:</strong>
  <%= @price.change_rate %>
</p>

<p>
  <strong>Bid:</strong>
  <%= @price.bid %>
</p>

<p>
  <strong>Wavg:</strong>
  <%= @price.wavg %>
</p>

<p>
  <strong>Last order:</strong>
  <%= @price.last_order %>
</p>

<p>
  <strong>Volume:</strong>
  <%= @price.volume %>
</p>

<p>
  <strong>Low:</strong>
  <%= @price.low %>
</p>

<p>
  <strong>Ask:</strong>
  <%= @price.ask %>
</p>

<p>
  <strong>Avg:</strong>
  <%= @price.avg %>
</p>

<%= link_to 'Edit', edit_price_path(@price) %> |
<%= link_to 'Back', prices_path %>